### ISSUE TITLE
Support for a EcmaScript module as config

### ISSUE THREAD

**Issue by SanjoSolutions** [iamyoki/playwright-watch#2]
package.json:

```json
{
   "private": true,
   "type": "module",
   "devDependencies": {
      "@playwright/test": "^1.14.1",
      "playwright-watch": "^1.3.19"
   }
}
```

playwright.config.js:
```javascript
export default {
  
}
```

command:
```shell
npx playwright-watch test
```

gives the error:
```
C:\Users\jonas\Desktop\tic-tac-toe\node_modules\cosmiconfig\dist\loaders.js:32
    throw error;
                                                          ^

Error [ERR_REQUIRE_ESM]: require() of ES Module C:\Users\jonas\Desktop\tic-tac-toe\playwright.config.js from C:\Users\jonas\
Desktop\tic-tac-toe\node_modules\cosmiconfig\dist\loaders.js not supported.
Instead change the require of playwright.config.js in C:\Users\jonas\Desktop\tic-tac-toe\node_modules\cosmiconfig\dist\loade
rs.js to a dynamic import() which is available in all CommonJS modules.
    at module.exports (C:\Users\jonas\Desktop\tic-tac-toe\node_modules\import-fresh\index.js:32:59)
    at loadJs (C:\Users\jonas\Desktop\tic-tac-toe\node_modules\cosmiconfig\dist\loaders.js:16:18)
    at ExplorerSync.loadFileContentSync (C:\Users\jonas\Desktop\tic-tac-toe\node_modules\cosmiconfig\dist\ExplorerSync.js:84
:26)
    at ExplorerSync.createCosmiconfigResultSync (C:\Users\jonas\Desktop\tic-tac-toe\node_modules\cosmiconfig\dist\ExplorerSy
nc.js:89:30)
    at ExplorerSync.loadSearchPlaceSync (C:\Users\jonas\Desktop\tic-tac-toe\node_modules\cosmiconfig\dist\ExplorerSync.js:70
:25)
    at ExplorerSync.searchDirectorySync (C:\Users\jonas\Desktop\tic-tac-toe\node_modules\cosmiconfig\dist\ExplorerSync.js:55
:32)
    at run (C:\Users\jonas\Desktop\tic-tac-toe\node_modules\cosmiconfig\dist\ExplorerSync.js:35:27)
    at cacheWrapperSync (C:\Users\jonas\Desktop\tic-tac-toe\node_modules\cosmiconfig\dist\cacheWrapper.js:28:18)
    at ExplorerSync.searchFromDirectorySync (C:\Users\jonas\Desktop\tic-tac-toe\node_modules\cosmiconfig\dist\ExplorerSync.j
s:47:49)
    at ExplorerSync.searchSync (C:\Users\jonas\Desktop\tic-tac-toe\node_modules\cosmiconfig\dist\ExplorerSync.js:27:25)
    at getWatchPath (C:\Users\jonas\Desktop\tic-tac-toe\node_modules\playwright-watch\lib\getWatchPath.js:5:22)
    at Object.defaultCommand [as handler] (C:\Users\jonas\Desktop\tic-tac-toe\node_modules\playwright-watch\commands\default
Command.js:7:9)
    at C:\Users\jonas\Desktop\tic-tac-toe\node_modules\playwright-watch\node_modules\yargs\build\index.cjs:1:9052
    at j (C:\Users\jonas\Desktop\tic-tac-toe\node_modules\playwright-watch\node_modules\yargs\build\index.cjs:1:4931)
    at M.applyMiddlewareAndGetResult (C:\Users\jonas\Desktop\tic-tac-toe\node_modules\playwright-watch\node_modules\yargs\bu
ild\index.cjs:1:9021)
    at M.runCommand (C:\Users\jonas\Desktop\tic-tac-toe\node_modules\playwright-watch\node_modules\yargs\build\index.cjs:1:7
206)
    at Bt.[runYargsParserAndExecuteCommands] (C:\Users\jonas\Desktop\tic-tac-toe\node_modules\playwright-watch\node_modules\
yargs\build\index.cjs:1:54693)
    at Bt.parse (C:\Users\jonas\Desktop\tic-tac-toe\node_modules\playwright-watch\node_modules\yargs\build\index.cjs:1:36968
)
    at Bt.get [as argv] (C:\Users\jonas\Desktop\tic-tac-toe\node_modules\playwright-watch\node_modules\yargs\build\index.cjs
:1:57661)
    at Object.<anonymous> (C:\Users\jonas\Desktop\tic-tac-toe\node_modules\playwright-watch\bin\playwright-watch.js:42:25) {
  code: 'ERR_REQUIRE_ESM'
}
```

It works when running Playwright directly with:
```shell
npx playwright test
```

**Comment by iamyoki** [comment]
❤️ I am so Sorry, supporting es module may not be the work that third-party modules need to support, but I welcome someone to pr this feature.
